{ pkgs }:

let
  table = import ./module-table.nix;

  ## Translate module-table.nix's external-deps strings into ASDF system
  ## names. Most names match; a few rename (the lispDeps map elsewhere uses
  ## the short forms, ASDF expects the upstream system names).
  asdfNameOf = n: {
    "jzon" = "com.inuoe.jzon";
    "lack-core" = "lack";
    "clack-session" = "lack-middleware-session";
    "clack-csrf" = "lack-middleware-csrf";
    "clack-static" = "lack-middleware-static";
    "clack-accesslog" = "lack-middleware-accesslog";
    "clack-cors" = "lack-middleware-cors";
  }.${n} or n;

  subsystemName = name: "lol-web/${name}";
  subsystemTestName = name: "lol-web/${name}/test";

  fileComponent = path:
    let stem = builtins.replaceStrings [ ".lisp" ] [ "" ] path;
    in ''(:file "${stem}")'';

  quoted = s: ''"${s}"'';

  indent = "               ";

  joinIndented = pkgs.lib.concatStringsSep ("\n" + indent);

  ## Sub-systems that have any test files. Used to gate per-sub-system test
  ## defsystems and the umbrella test's :depends-on list.
  subsystemsWithTests =
    builtins.filter (n: table.modules.${n}.test-srcs != []) table.load-order;

  ## Emit one ASDF defsystem form per sub-system, with focused :depends-on
  ## (internal-deps as sibling lol-web/<n> systems, external-deps mapped to
  ## ASDF names) and per-module components (package-src first, then srcs).
  subsystemDefsystem = name:
    let
      cfg = table.modules.${name};
      depsList =
        map subsystemName cfg.internal-deps
        ++ map asdfNameOf cfg.external-deps;
      components = [ cfg.package-src ] ++ cfg.srcs;
    in ''
      (defsystem "${subsystemName name}"
        :depends-on (${joinIndented (map quoted depsList)})
        :pathname "."
        :serial t
        :components (${joinIndented (map fileComponent components)}))
    '';

  ## Per-sub-system test defsystem. Loads only the sub-system + fiveam +
  ## any test-internal-deps, then the test files for that sub-system.
  ## Calling test-op on this system runs just that sub-system's suite —
  ## equivalent to `nix build … "lol-web/<n>"` under the buildLisp side.
  subsystemTestDefsystem = name:
    let
      cfg = table.modules.${name};
      testInternal = cfg.test-internal-deps or [];
      depsList = [ (subsystemName name) "fiveam" ]
              ++ map subsystemName testInternal;
    in ''
      (defsystem "${subsystemTestName name}"
        :depends-on (${joinIndented (map quoted depsList)})
        :pathname "."
        :serial t
        :components (${joinIndented (map fileComponent cfg.test-srcs)})
        :perform (test-op (op c)
                   (uiop:symbol-call :${subsystemTestName name} :run-tests)))
    '';

  ## The umbrella system depends on every sub-system in load-order and only
  ## compiles the umbrella file (src/package.lisp), which defines :lol-web
  ## and the :lol-reactive shim. Sub-system load order is enforced by ASDF
  ## walking the :depends-on list in order.
  umbrellaDefsystem = ''
    (defsystem "lol-web"
      :description "Reactive web framework using Let Over Lambda patterns."
      :license "MIT"
      :depends-on (${joinIndented (map (n: quoted (subsystemName n)) table.load-order)})
      :pathname "."
      :serial t
      :components (${fileComponent table.umbrella-src})
      :in-order-to ((test-op (test-op "lol-web/test"))))
  '';

  ## Umbrella test system: depends on the umbrella + every sub-system test
  ## system, so loading "lol-web/test" pulls in every per-sub-system test
  ## suite. The umbrella's own components are the shim-parity tests + the
  ## run-all-tests aggregator.
  umbrellaTestDeps =
    [ "lol-web" "fiveam" ]
    ++ map subsystemTestName subsystemsWithTests;

  umbrellaTestDefsystem = ''
    (defsystem "lol-web/test"
      :depends-on (${joinIndented (map quoted umbrellaTestDeps)})
      :pathname "."
      :serial t
      :components (${joinIndented (map fileComponent table.umbrella-test-srcs)})
      :perform (test-op (op c)
                 (uiop:symbol-call :lol-web/test :run-all-tests)))
  '';

  asd = ''
    ;;;; lol-web.asd — generated by asdf.nix from module-table.nix.
    ;;;; Edit module-table.nix and regenerate; do not edit this file by hand.
    ;;;;
    ;;;; Defines one ASDF system per :lol-web/<sub> sub-system plus an umbrella
    ;;;; :lol-web system. Each sub-system's :depends-on lists only the
    ;;;; libraries it actually needs; loading "lol-web/<sub>" pulls a focused
    ;;;; closure rather than the full umbrella's transitive deps.
    ;;;;
    ;;;; Test systems mirror the same shape: :lol-web/<sub>/test depends only
    ;;;; on its sub-system + fiveam; :lol-web/test depends on the umbrella
    ;;;; plus every sub-system's test system, and runs every suite via
    ;;;; (lol-web/test:run-all-tests).

    ${umbrellaDefsystem}
    ${pkgs.lib.concatMapStrings subsystemDefsystem table.load-order}
    ${pkgs.lib.concatMapStrings subsystemTestDefsystem subsystemsWithTests}
    ${umbrellaTestDefsystem}
  '';
in
pkgs.writeText "lol-web.asd" asd
